version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: cdec/minimal-serializer-dev:0.2.4

commands:
  build:
    parameters:
      id:
        type: string
      compiler:
        type: string
      cpp:
        type: integer
    steps:
      - checkout
      - run:
          name: Make build directory
          command: mkdir build_<< parameters.id >>
      - run:
          name: Create build files
          working_directory: build_<< parameters.id >>
          command: cmake .. -DCMAKE_CXX_COMPILER=<< parameters.compiler >> -DCMAKE_CXX_STANDARD=<<parameters.cpp>>
      - run:
          name: Build binaries
          working_directory: build_<< parameters.id >>
          command: make
      - persist_to_workspace:
          root: "."
          paths:
            - "build_<< parameters.id >>"

  test:
    parameters:
      id:
        type: string
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: Execute unit tests
          working_directory: build_<< parameters.id >>
          command: BOOST_TEST_LOGGER="JUNIT,,minimal_serializer_cpp_test_<< parameters.id >>_log.xml" ctest
      - run:
          name: Copy test log
          command: |
            mkdir -p ~/test-results/junit/
            cp build_<< parameters.id >>/minimal_serializer_cpp_test/minimal_serializer_cpp_test_<< parameters.id >>_log.xml ~/test-results/junit/
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

jobs:
  build_gpp_cpp17:
    executor: default
    steps:
      - build:
          id: g++-c++17
          compiler: g++
          cpp: 17

  build_clang_cpp17:
    executor: default
    steps:
      - build:
          id: clang-c++17
          compiler: clang++
          cpp: 17

  build_gpp_cpp20:
    executor: default
    steps:
      - build:
          id: g++-c++20
          compiler: g++
          cpp: 20

  build_clang_cpp20:
    executor: default
    steps:
      - build:
          id: clang-c++20
          compiler: clang++
          cpp: 20

  test_gpp_cpp17:
    executor: default
    steps:
      - test:
          id: g++-c++17

  test_clang_cpp17:
    executor: default
    steps:
      - test:
          id: clang-c++17

  test_gpp_cpp20:
    executor: default
    steps:
      - test:
          id: g++-c++20

  test_clang_cpp20:
    executor: default
    steps:
      - test:
          id: clang-c++20

workflows:
  build_and_test:
    jobs:
      - build_gpp_cpp17:
          filters:
            branches:
              only: master

      - build_clang_cpp17:
          filters:
            branches:
              only: master

      - build_gpp_cpp20:
          filters:
            branches:
              only: master

      - build_clang_cpp20:
          filters:
            branches:
              only: master

      - test_gpp_cpp17:
          requires:
            - build_gpp_cpp17
          filters:
            branches:
              only: master

      - test_clang_cpp17:
          requires:
            - build_clang_cpp17
          filters:
            branches:
              only: master

      - test_gpp_cpp20:
          requires:
            - build_gpp_cpp20
          filters:
            branches:
              only: master

      - test_clang_cpp20:
          requires:
            - build_clang_cpp20
          filters:
            branches:
              only: master
